// Code generated by "stringer -type Level -linecomment --output level-string.go"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fatal-0]
	_ = x[Error-1]
	_ = x[Warn-2]
	_ = x[Info-3]
	_ = x[Debug-4]
	_ = x[Trace-5]
}

const _Level_name = "FATALERRORWARNINFODEBUGTRACE"

var _Level_index = [...]uint8{0, 5, 10, 14, 18, 23, 28}

func (i Level) String() string {
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
